// Run against TestBrowserPreview only. All people and credentials are synthetic.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/tmp/verify-link-browser/playwright-core');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const root='/src/test-results';
(async()=>{fs.mkdirSync(root,{recursive:true});const chrome=fs.readdirSync('/ms-playwright').find(n=>/^chromium-/.test(n));const executablePath='/ms-playwright/'+chrome+'/chrome-linux64/chrome';const browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox']});
try{const ctx=await browser.newContext({viewport:{width:1440,height:1100},httpCredentials:{username:'agent@example.test',password:'local-test-password'}});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&m.text().includes('Content Security Policy'))errors.push(m.text());});
await page.goto('http://127.0.0.1:18092/console');await page.getByText('Live · updates every 2s',{exact:true}).waitFor();await page.screenshot({path:root+'/console-desktop.png',fullPage:true});
await page.locator('#recipient').fill('Synthetic customer on Signal');await page.locator('[name=expected_name]').fill('Anna Larsen');await page.locator('[name=case_ref]').fill('TEST-1042');await page.getByRole('button',{name:'Send request'}).click();await page.locator('#copy-result').waitFor({state:'visible'});const link=await page.locator('#copy-link').inputValue();assert(link.includes('/v/'));
const recipient=await browser.newContext({viewport:{width:412,height:915}});const phone=await recipient.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto(link);await phone.getByRole('button',{name:'Verify with your EU wallet'}).waitFor();assert(await phone.locator('body').evaluate(el=>el.scrollWidth<=innerWidth));await phone.screenshot({path:root+'/handoff-mobile.png',fullPage:true});
await phone.getByRole('button',{name:'Verify with your EU wallet'}).click();await phone.getByText('Done. You can go back to your chat.',{exact:true}).waitFor({timeout:15000});await page.getByText('Anna Larsen',{exact:true}).waitFor({timeout:15000});await page.screenshot({path:root+'/console-verified.png',fullPage:true});
const replay=await phone.request.post(link+'/start',{headers:{Origin:'http://127.0.0.1:18092'}});assert.equal(replay.status(),410);const hidden=await phone.request.get('http://127.0.0.1:18092/ui/presentations');assert.equal(hidden.status(),404);
await page.setViewportSize({width:412,height:915});assert(await page.locator('body').evaluate(el=>el.scrollWidth<=innerWidth));await page.screenshot({path:root+'/console-mobile.png',fullPage:true});
const exported=await page.request.get('http://127.0.0.1:18092/api/sessions/export.csv');const csv=await exported.text();assert(!csv.includes('Anna')&&!csv.includes('Synthetic customer'));assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: console create, mobile layout, wallet handoff, result polling, replay refusal, private route isolation, CSV, CSP and JavaScript');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
