"use strict";
const $ = (s) => document.querySelector(s);
const names = {copylink:"Copy a link",whatsapp:"WhatsApp",telegram:"Telegram",sms:"SMS",email:"Email"};
const errors = {invalid_recipient:"Check the customer’s number or address.",unknown_preset:"Choose a supported request.",preset_not_registered:"The hosted EUDI registration supports the name check. Age checks need a separate registration.",name_not_requested:"An age check does not request a name.",rate_limited:"Too many requests. Please try again shortly.",whatsapp_window_closed:"This customer hasn't messaged you in the last 24 hours. Ask them to send VERIFY to your WhatsApp number, or set up an approved template.",send_failed:"The message could not be sent. Check the channel setup and try again.",unauthorized:"Your sign-in has expired. Reload this page to sign in.",forbidden:"Your role does not allow this action."};
const demoMode=document.body.dataset.demo==="true";
let me, channels = [], timer, copyTimer;
const openDetails = new Set();
const node = (tag, cls, text) => {const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
function toast(text){$("#toast").textContent=text;$("#toast").hidden=false;setTimeout(()=>$("#toast").hidden=true,4500);}
async function api(path, options={}) {const r=await fetch(path,{cache:"no-store",...options,headers:{"Content-Type":"application/json",...options.headers}});let body;try{body=await r.json();}catch{throw Error("The service is unavailable. Please try again.");}if(!r.ok)throw Error(errors[body.error]||"This request could not be completed ("+(body.error||r.status)+").");return body;}
function selectedChannel(){return $("input[name=channel]:checked")?.value||"copylink";}
function updateForm(){const c=selectedChannel(), age=$("input[name=preset]:checked").value==="over-18";$("#claim-help").textContent=age?"The customer shares whether they are 18 or older. No name or date of birth.":"The customer shares their given name and family name.";$("#expected-field").hidden=age;$("#expected-help").hidden=age;$("[name=expected_name]").disabled=age;
const p=$("#recipient");p.type=c==="email"?"email":"text";p.removeAttribute("pattern");p.maxLength=c==="copylink"?100:320;p.placeholder={copylink:"A label, e.g. Anna on Signal",whatsapp:"+4521216602",sms:"+4521216602",email:"anna@example.com",telegram:"Numeric chat ID"}[c];if(c==="sms"||c==="whatsapp")p.pattern="\\+[1-9][0-9]{7,14}";if(c==="telegram")p.pattern="-?[1-9][0-9]{0,19}";
$("#recipient-help").textContent={copylink:"Give this link a label so you can find it later.",sms:"Use international format, including the country code.",whatsapp:"The customer must have messaged you, or an approved template is needed.",email:"One email address.",telegram:"Choose a recent private chat, or enter its numeric ID."}[c];$("#recent-chats").replaceChildren();if(c==="telegram")for(const id of channels.find(x=>x.id===c)?.recent_chats||[]){const o=node("option");o.value=id;$("#recent-chats").append(o);}}
function query(){const p=new URLSearchParams();if($("#status-filter").value)p.set("status",$("#status-filter").value);if($("#channel-filter").value)p.set("channel",$("#channel-filter").value);if($("#mine-filter").checked)p.set("mine","true");return p.toString();}
function date(t){return !t||t.startsWith("0001")?"—":new Date(t).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"});}
function showLink(data){if($("#try-demo-link"))$("#try-demo-link").href=data.link||"/console";clearTimeout(copyTimer);$("#copy-link").value=data.link||"";$("#copy-result").hidden=!data.link;if(data.link)copyTimer=setTimeout(clearLink,Math.max(0,new Date(data.expires_at)-Date.now()));}
function clearLink(){if($("#try-demo-link"))$("#try-demo-link").removeAttribute("href");clearTimeout(copyTimer);$("#copy-link").value="";$("#copy-result").hidden=true;}
function resultText(s){if(s.result_wiped)return "Result cleared";if(s.result&&new Date(s.result_wipe_at)<=new Date())return "Result cleared";if(s.result){if(s.preset==="over-18")return "Over 18: "+(s.result.age_over_18?"yes":"no");const name=[s.result.given_name,s.result.family_name].filter(Boolean).join(" ");return s.status==="mismatch"?(demoMode?"Simulated mismatch: ":"Verified as a different person: ")+name+(demoMode?". Compare it with the expected name.":". The link may have been forwarded. Do not proceed."):name;}return {sent:"Waiting for the customer",created:"Sending…",verifying:demoMode?"Waiting for a sample wallet choice":"The wallet check is in progress",expired:s.started_at&&!s.started_at.startsWith("0001")?"The wallet check timed out.":"The link expired before it was used.",declined:"The customer declined to share.",failed:"Verification failed: "+(s.error_code||"verification_error"),cancelled:"Request cancelled."}[s.status]||"Result cleared";}
async function action(s,kind,button){button.disabled=true;try{const data=await api("/api/sessions/"+encodeURIComponent(s.id)+"/"+kind,{method:"POST",body:"{}"});if(kind==="resend")showLink(data);toast(kind==="cancel"?"Request cancelled":"New request sent");await refresh();}catch(e){toast(e.message);}finally{button.disabled=false;}}
function render(items){const list=$("#activity-list");list.replaceChildren();$("#count").textContent=items.length;if(!items.length){const empty=node("div","empty");empty.append(node("div","empty-symbol","↗"),node("h3","","The next conversation starts here."),node("p","","Send a request. Its progress and verified result will appear here."));list.append(empty);return;}
for(const s of items){const row=node("article","request"),head=node("div","request-head"),status=s.status==="sent"&&s.opened_at&&!s.opened_at.startsWith("0001")?"opened":s.status;head.append(node("span","customer",s.recipient),node("span","badge "+s.status,(demoMode?"Demo · ":"")+status[0].toUpperCase()+status.slice(1)));row.append(head,node("div","request-meta",[names[s.channel],s.preset==="over-18"?"Over 18":"Name",s.case_ref?"Case "+s.case_ref:null].filter(Boolean).join(" · ")));
const result=node("p","result",resultText(s));if(s.result&&!s.result_wiped)result.dataset.wipe=s.result_wipe_at;row.append(result,node("div","request-meta","Sent "+date(s.created_at)+" by "+(s.sent_by?s.sent_by.split("@")[0]:"customer")+(s.seconds_to_verified?" · "+Math.round(s.seconds_to_verified)+"s to verify":"")));
const actions=node("div","request-actions");if(["created","sent","verifying"].includes(s.status)){const b=node("button","text-button","Cancel");b.type="button";b.onclick=()=>action(s,"cancel",b);actions.append(b);}if(me.role==="supervisor"&&["expired","declined","failed"].includes(s.status)){const b=node("button","text-button","Resend");b.type="button";b.onclick=()=>action(s,"resend",b);actions.append(b);}const details=node("details"),summary=node("summary","text-button","Details");details.open=openDetails.has(s.id);details.addEventListener("toggle",()=>{if(details.open)openDetails.add(s.id);else openDetails.delete(s.id);});details.append(summary,node("div","timeline",["Created: "+date(s.created_at),"Opened: "+date(s.opened_at),"Started: "+date(s.started_at),"Completed: "+date(s.completed_at)].join("\n")));actions.append(details);row.append(actions);list.append(row);}}
async function refresh(){try{const items=await api("/api/sessions?"+query());render(items);$("#connection").textContent="Live · updates every 2s";$("#export").href="/api/sessions/export.csv?"+query();}catch(e){$("#connection").textContent="Connection interrupted";$("#activity-list").replaceChildren(node("p","error",e.message));}finally{clearTimeout(timer);if(!document.hidden)timer=setTimeout(refresh,2000);}}
$("#send-form").addEventListener("change",updateForm);$("#send-form").addEventListener("submit",async e=>{e.preventDefault();$("#send").disabled=true;$("#form-error").hidden=true;const f=new FormData(e.target),body={channel:selectedChannel(),recipient:f.get("recipient").trim(),preset:f.get("preset"),expected_name:f.get("expected_name")?.trim()||"",case_ref:f.get("case_ref")?.trim()||""};try{const data=await api("/api/sessions",{method:"POST",body:JSON.stringify(body)});showLink(data);toast("Request sent to "+data.recipient);await refresh();}catch(err){$("#form-error").textContent=err.message;$("#form-error").hidden=false;}finally{$("#send").disabled=false;}});
for(const id of ["#status-filter","#channel-filter","#mine-filter"])$(id).addEventListener("change",refresh);
$("#copy-button").onclick=async()=>{try{await navigator.clipboard.writeText($("#copy-link").value);toast("Link copied");}catch{$("#copy-link").select();toast("Select and copy the link above.");}};$("#dismiss-link").onclick=clearLink;
document.addEventListener("visibilitychange",()=>{if(document.hidden){clearTimeout(timer);$("#activity-list").replaceChildren();}else refresh();});window.addEventListener("pagehide",()=>{clearTimeout(timer);clearLink();$("#activity-list").replaceChildren();});window.addEventListener("pageshow",e=>{if(e.persisted)refresh();});
setInterval(()=>{for(const el of document.querySelectorAll("[data-wipe]"))if(new Date(el.dataset.wipe)<=new Date()){el.textContent="Result cleared";delete el.dataset.wipe;}},500);
if(demoMode){$("#recipient").value="Demo customer";$("[name=expected_name]").value="Alex Demo";$("[name=case_ref]").value="DEMO-001";$("#send").firstChild.textContent="Create demo link ";}
(async()=>{try{[me,channels]=await Promise.all([api("/api/me"),api("/api/channels")]);$("#identity").textContent=me.email.split("@")[0]+" · "+me.role;$("#export").hidden=me.role!=="supervisor";$("#mine-filter").checked=me.role!=="supervisor";$("#mine-filter").disabled=me.role!=="supervisor";for(const [i,c]of channels.entries()){const label=node("label"),input=node("input");input.type="radio";input.name="channel";input.value=c.id;input.checked=i===0;label.append(input,node("span","",names[c.id]));$("#channels").append(label);const o=node("option","",names[c.id]);o.value=c.id;$("#channel-filter").append(o);}$("#message-preview").textContent=document.body.dataset.business+" asked to confirm your identity. Open this link to verify with your EU wallet: [verification link]\nThe link works once and expires in "+document.body.dataset.minutes+" minutes. If you did not expect this, ignore it.";if(demoMode)$("#message-preview").textContent="Try this synthetic message verifier demo: [demo link]. No real wallet or messages are involved.";updateForm();await refresh();}catch(e){$("#form-error").textContent=e.message;$("#form-error").hidden=false;$("#send").disabled=true;}})();
